--1--
CREATE TABLE ContaBank(
ContaID INT IDENTITY PRIMARY KEY,
Nome VARCHAR(150) NOT NULL,
Idade INT CHECK( Idade >= 18) NOT NULL,
CPF INT UNIQUE NOT NULL
);

--2--
CREATE TABLE Kids(
KidsID INT  IDENTITY PRIMARY KEY,
Nome VARCHAR(150) NOT NULL,
Idade INT CHECK(Idade <= 16) NOT NULL
);
